apiVersion: v1
data:
  PROVIDER_URL: {{ .Values.provider.url }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: hardhat-mainnet-sandbox-env
  name: hardhat-mainnet-sandbox-env
