apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: hardhat-mainnet-sandbox
  name: hardhat-mainnet-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hardhat-mainnet-sandbox
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: hardhat-mainnet-sandbox
    spec:
      containers:
        - args:
            - sh
            - ./entrypoint.sh
          env:
            - name: PROVIDER_URL
              valueFrom:
                configMapKeyRef:
                  key: PROVIDER_URL
                  name: hardhat-mainnet-sandbox-env
          image: benjaminlu/hardhat-mainnet-sandbox:1.0.0
          name: hardhat-mainnet-sandbox
          ports:
            - containerPort: 8545
          resources: {}
          workingDir: /root/hardhat-mainnet-sandbox
      restartPolicy: Always
status: {}
